### ISSUE TITLE
[BUG] (代理) 起動時にFileNotFoundExceptionで落ちる

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#126]
### Describe the bug

起動時にFileNotFoundExceptionで落ちるそう。

これから私も再現確認します

### To Reproduce

起動するのみ(らしい)です

### Crash Reports

[crash-2021-08-15_19.47.56-client.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/6987986/crash-2021-08-15_19.47.56-client.txt)

### OS

Windows 10 (amd64) version 10.0

### KaizPatchX Version

1.3.0

### Other Mods

クラレポ参考

**Comment by anatawa12** [comment]
Reproduced with macos 11.5.1

**Comment by Kai-Z-JP** [comment]
キャッシュが関係しているような気がするのでjar-mods-cacheとfixrtm-cacheフォルダの削除試していただいても大丈夫ですか？

**Comment by anatawa12** [comment]
作成されてなさそうです。

**Comment by anatawa12** [comment]
jar-mods-cacheとfixrtm-cacheは生成されてなさそうです。

**Comment by Kai-Z-JP** [comment]
🤔

**Comment by anatawa12** [comment]
ログより関係の有りそうなエラーを見つけました

```
trying to construct model pack: extrautilities-1.2.12.jar
java.lang.NoClassDefFoundError: Could not initialize class jp.kaiz.kaizpatch.fixrtm.util.ArrayPool$Companion$pByte$1$1
	at jp.kaiz.kaizpatch.fixrtm.util.ArrayPool.pByte$lambda-1(ArrayPool.kt:59)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at jp.kaiz.kaizpatch.fixrtm.util.ArrayPool$Companion.getBytePool(ArrayPool.kt:65)
	at jp.kaiz.kaizpatch.fixrtm.util.DigestUtils.sha1Hex(DigestUtils.kt:26)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader$ZipModelPack.<init>(FIXFileLoader.kt:84)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader$ZipModelPack.<init>(FIXFileLoader.kt:81)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader.loadModelPack(FIXFileLoader.kt:64)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader.<clinit>(FIXFileLoader.kt:28)
	at jp.ngt.rtm.RTMCore.construct(RTMCore.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by anatawa12** [comment]
```
trying to construct model pack: CustomNPCs_1.7.10d(29oct17).jar
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at jp.kaiz.kaizpatch.fixrtm.util.ArrayPool$Companion$pByte$1$1.<init>(ArrayPool.kt)
	at jp.kaiz.kaizpatch.fixrtm.util.ArrayPool$Companion$pByte$1$1.<clinit>(ArrayPool.kt)
	at jp.kaiz.kaizpatch.fixrtm.util.ArrayPool.pByte$lambda-1(ArrayPool.kt:59)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at jp.kaiz.kaizpatch.fixrtm.util.ArrayPool$Companion.getBytePool(ArrayPool.kt:65)
	at jp.kaiz.kaizpatch.fixrtm.util.DigestUtils.sha1Hex(DigestUtils.kt:26)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader$ZipModelPack.<init>(FIXFileLoader.kt:84)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader$ZipModelPack.<init>(FIXFileLoader.kt:81)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader.loadModelPack(FIXFileLoader.kt:64)
	at jp.kaiz.kaizpatch.fixrtm.modelpack.FIXFileLoader.<clinit>(FIXFileLoader.kt:28)
	at jp.ngt.rtm.RTMCore.construct(RTMCore.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by anatawa12** [comment]
おそらくですが、他のmodとの互換性問題ですね。kotlinのバージョンが複数classpathに存在するとこのようなエラーになった記憶があります。

**Comment by Kai-Z-JP** [comment]
なるほど...

**Comment by Kai-Z-JP** [comment]
古いバージョンのKotlinが読み込まれてるときにanatawa12/preload-newer-kotlinへのリンクとともにクラッシュするようにしました
