### ISSUE TITLE
[BUG] get kicked when select the model of any blocks

### ISSUE THREAD

**Issue by anatawa12** [Kai-Z-JP/KaizPatchX#146]
### Describe the bug

get kicked when select the model of any blocks.

```
[14:23:08 WARN]: More than one exception was raised. Will report only the first one and log others.
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:182) [SimpleNetworkWrapper.class:1.7.10-28]
	at jp.ngt.rtm.rail.TileEntityLargeRailCore.sendPacket(TileEntityLargeRailCore.java:201) [TileEntityLargeRailCore.class:?]
	at jp.ngt.rtm.rail.TileEntityLargeRailCore.func_145844_m(TileEntityLargeRailCore.java:196) [TileEntityLargeRailCore.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:721) [mw.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:380) [mw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2706) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:878) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2644) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2460) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:674) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:835) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
```
```
[13:53:22] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel RTM
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:182) ~[SimpleNetworkWrapper.class:1.7.10-28]
	at jp.ngt.rtm.rail.TileEntityLargeRailCore.sendPacket(TileEntityLargeRailCore.java:201) ~[TileEntityLargeRailCore.class:?]
	at jp.ngt.rtm.rail.TileEntityLargeRailCore.func_145844_m(TileEntityLargeRailCore.java:196) ~[TileEntityLargeRailCore.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:721) ~[mw.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:380) ~[mw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2706) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:878) ~[mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2644) ~[ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2460) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:674) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:835) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
	at jp.ngt.rtm.network.PacketLargeRailCore.toBytes(PacketLargeRailCore.java:81) ~[PacketLargeRailCore.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:1.7.10-28]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-28]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-28]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
	... 22 more
```

### To Reproduce

select the model of any blocks

### OS

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-81-generic x86_64)

### KaizPatchX Version

1.3.0

### Other Mods

Mohist環境

**Comment by Kai-Z-JP** [comment]
修正しました
