### ISSUE TITLE
[BUG] パケットによってサーバーからキックされる

### ISSUE THREAD

**Issue by Kai-Z-JP** [Kai-Z-JP/KaizPatchX#281]
### Describe the bug

不明

### To Reproduce

不明

### Crash Reports

23:49:54.080
FML
Client thread
There was a critical exception handling a packet on channel NGTLib
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1445)
	at jp.ngt.ngtlib.network.PacketNBT.onGetPacket(PacketNBT.java:92)
	at jp.ngt.ngtlib.network.PacketNBTHandlerClient.onMessage(PacketNBTHandlerClient.java:18)
	at jp.ngt.ngtlib.network.PacketNBTHandlerClient.onMessage(PacketNBTHandlerClient.java:9)
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at jp.ngt.rtm.entity.train.util.Formation.setEntry(Formation.java:90)
	at jp.ngt.rtm.entity.train.util.Formation.setTrain(Formation.java:105)
	at jp.ngt.rtm.entity.train.EntityTrainBase.readFormationData(EntityTrainBase.java:173)
	at jp.ngt.rtm.entity.train.EntityTrainBase.func_70037_a(EntityTrainBase.java:153)
	at jp.ngt.rtm.entity.train.EntityTrain.func_70037_a(EntityTrain.java:22)
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1433)
	... 30 more

### OS

不明

### KaizPatchX Version

1.5.0-rc.2

**Comment by Kai-Z-JP** [comment]
同様の問題が半年間起きなかったので一旦クローズ
