### ISSUE TITLE
CI: Testが通らない

### ISSUE THREAD

**Issue by Kai-Z-JP** [Kai-Z-JP/KaizPatchX#327]
```
[mc-image-helper] 02:46:54.024 INFO  : Running Forge installer. This might take a while...
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1942)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1941)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:15[11](https://github.com/Kai-Z-JP/KaizPatchX/actions/runs/3382627336/jobs/5617754598#step:6:12))
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:368)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:356)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:151)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:75)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:55)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:93)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:68)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
[init] ERROR failed to install forge
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3058)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:305)
	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:[13](https://github.com/Kai-Z-JP/KaizPatchX/actions/runs/3382627336/jobs/5617754598#step:6:14)8)
	... 4 more
	```

**Comment by Kai-Z-JP** [comment]
https://github.com/itzg/docker-minecraft-server/issues/1814
