### ISSUE TITLE
[BUG] it looks bug

### ISSUE THREAD

**Issue by zzxxqwer** [Kai-Z-JP/KaizPatchX#329]
### Describe the bug

I downloaded the RTM compatible map from the Internet, unzipped it, and put it in the save file, but it came out that there were no 2 blocks/items, but I ignored it and ran it, and the game stopped and crashed.

### To Reproduce

1. run the game
2. Load the save file
3. A warning window appears because there are no two files in the middle.
4. Ignored and executed
5. Game freezes and crashes

### Expected behavior

I just thought it would work

### Actual Behavior

The game crashed and crashed with an error

### Screenshots

![image](https://user-images.githubusercontent.com/98940121/199910433-714df97e-5b30-4868-ada9-9ddb3f263173.png)

### Crash Reports

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 22. 11. 4 오후 3:42
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1252)
	at jp.ngt.ngtlib.world.NGTWorld.lambda$loadEntity$1(NGTWorld.java:103)
	at jp.ngt.ngtlib.world.NGTWorld$$Lambda$198/1791594834.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at jp.ngt.ngtlib.world.NGTWorld.loadEntity(NGTWorld.java:103)
	at jp.ngt.ngtlib.world.NGTWorld.<init>(NGTWorld.java:71)
	at jp.ngt.mcte.world.MCTEWorld.<init>(MCTEWorld.java:19)
	at jp.ngt.mcte.block.TileEntityMiniature.getDummyWorld(TileEntityMiniature.java:92)
	at jp.ngt.mcte.block.TileEntityMiniature.func_145845_h(TileEntityMiniature.java:86)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.forEach(ArrayList.java:1252)
	at jp.ngt.ngtlib.world.NGTWorld.lambda$loadEntity$1(NGTWorld.java:103)
	at jp.ngt.ngtlib.world.NGTWorld$$Lambda$198/1791594834.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at jp.ngt.ngtlib.world.NGTWorld.loadEntity(NGTWorld.java:103)
	at jp.ngt.ngtlib.world.NGTWorld.<init>(NGTWorld.java:71)
	at jp.ngt.mcte.world.MCTEWorld.<init>(MCTEWorld.java:19)
	at jp.ngt.mcte.block.TileEntityMiniature.getDummyWorld(TileEntityMiniature.java:92)
	at jp.ngt.mcte.block.TileEntityMiniature.func_145845_h(TileEntityMiniature.java:86)

-- Block entity being ticked --
Details:
	Name: TEMiniature // jp.ngt.mcte.block.TileEntityMiniature
	Block type: ID #668 (tile.mcte:miniature // jp.ngt.mcte.block.BlockMiniature)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (222,60,144), Chunk: (at 14,3,0 in 13,9; contains blocks 208,0,144 to 223,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #668 (tile.mcte:miniature // jp.ngt.mcte.block.BlockMiniature)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: 日本都?/椎葉? KAGOME_Map -카곰- <시이바현>
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 629 Drop: 0
	Level seed: -5861207548547092598
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (199,16,247), Chunk: (at 7,1,7 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 39310604 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 94171 (now: false), thunder time: 113123 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3872501160 bytes (3693 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 103
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	intelliinput{2.3.2} [IntelliInput for 1.7.10] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	MCTE{1.7.10.16 KaizPatchX/1.6.0} [MCTerrainEditor] (src1.7.10_20200822+KaizPatchX-1.6.0.jar) 
	UCHIJAAAA	NGTLib{1.7.10.32 KaizPatchX/1.6.0} [NGTLib] (src1.7.10_20200822+KaizPatchX-1.6.0.jar) 
	UCHIJAAAA	RTM{1.7.10.41 KaizPatchX/1.6.0} [RealTrainMod] (src1.7.10_20200822+KaizPatchX-1.6.0.jar) 
	UCHIJAAAA	stationsMod{1.7.10.5} [Stations Mod] (StationsMod-1.7.10.5.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

### OS

windows 10

### KaizPatchX Version

1.6.0

### Other Mods

stationmod

**Comment by PC28K** [comment]
not bug
![image](https://user-images.githubusercontent.com/41824434/200090330-b37362eb-b5bd-4b07-84a4-95d38ff9fe7a.png)
