### ISSUE TITLE
[BUG]レールコピー機能を使用した場合に一部の場合でクラッシュが発生する

### ISSUE THREAD

**Issue by Yuzuringo** [Kai-Z-JP/KaizPatchX#390]
### Describe the bug

1.7.0-rc1にてレールコピー機能を使用中に突然クラッシュしました。
再検証しましたが同様の状況が発生しました。なお、少なくとも1.6.2でも同様のクラッシュが発生する模様です。

### To Reproduce

①レールコピー機能で複数の形状の線路をアイテム化
②複数度にわたりレールコピー機能を使用し敷設
③クラッシュ

### Expected behavior

ログを見たところレールをコピーしたデータの読出し中に何らかの原因で範囲外の値を参照してしまうのが原因とみられます。
Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: 0
	at jp.ngt.rtm.rail.TileEntityLargeRailSwitchCore.readRailData(TileEntityLargeRailSwitchCore.java:52)
	at jp.ngt.rtm.rail.TileEntityLargeRailCore.func_145839_a(TileEntityLargeRailCore.java:68)
	at jp.ngt.rtm.rail.TileEntityLargeRailSwitchCore.func_145839_a(TileEntityLargeRailSwitchCore.java:25)
	at jp.ngt.ngtlib.block.TileEntityCustom.onDataPacket(TileEntityCustom.java:22)
	at jp.ngt.rtm.rail.TileEntityLargeRailCore.onDataPacket(TileEntityLargeRailCore.java:188)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1144)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Crash Reports

こちらが1.7.0-rc1です。[crash-2023-04-18_11.00.33-client.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/11257258/crash-2023-04-18_11.00.33-client.txt)
こちらが1.6.2です。
[crash-2023-04-18_10.46.11-server.txt](https://github.com/Kai-Z-JP/KaizPatchX/files/11258867/crash-2023-04-18_10.46.11-server.txt)

### OS

Windows 10 Home

### KaizPatchX Version

1.6.2 and 1.7.0-rc1

### Other Mods

Optifine,ATSAssistmod-1.7.10-1.7.4,SignalControllerMod-mc1.7.10-1.4.0

**Comment by Kai-Z-JP** [comment]
crash-2023-04-16_16.08.56-client.txtのクラッシュにつきましては、列車のコントロールパネルを開いたときのクラッシュであり、これは1.7.0-beta.1で修正済みです。

**Comment by Yuzuringo** [comment]
失礼いたしました。
